name: 🚀 NGINX-PARTY Release (🛠️ Stable + QUIC + Mods)

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-party-${{ env.NGINX_VERSION }}.deb
          path: nginx-${{ env.NGINX_VERSION }}-src/*.deb

      - name: 🐳 Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:${{ env.NGINX_VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:${{ env.NGINX_VERSION }} ghcr.io/${{ github.repository_owner }}/nginx-party:${{ env.NGINX_VERSION }}

      - name: 🚀 Push Docker images
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-party:${{ env.NGINX_VERSION }}
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:${{ env.NGINX_VERSION }}