name: 📦 NGINX-PARTY Release 🎉⚡

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ⚡ Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🛠️ Build & Test NGINX
        run: |
          echo "Building NGINX-PARTY for release..."
          ./ci.yml # Or replicate build steps here
          echo "✅ Build finished"

      - name: 🐼 Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nginx-party-release-artifacts
          path: |
            nginx-${{ env.NGINX_VERSION }}-src
            ModSecurity

      - name: 🚀 Publish Release Notes
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "NGINX-PARTY Release ${{ github.ref_name }} 🐼✨"
          body: |
            Stable NGINX-PARTY build with QUIC, ModSecurity, AVIF/WEBP, Websocket & Streams.
            Modules: ngx_brotli, ngx_cache_purge, ngx_fancyindex
          draft: false
          prerelease: false