name: 🐼 NGINX-PARTY Release Builder 🚀

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Checkout repository
        uses: actions/checkout@v4

      - name: 🐼 Download artifacts from CI
        uses: actions/download-artifact@v4
        with:
          name: nginx-artifacts
          path: ./build

      - name: 📦 Package release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir -p release
          cp -r build/* release/
          tar -czvf release/nginx-party-${VERSION}.tar.gz -C release .

      - name: 🚀 Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/nginx-party-${VERSION}.tar.gz
          asset_name: nginx-party-${VERSION}.tar.gz
          asset_content_type: application/gzip
