name: 🌌 Release NGINX-PARTY

on:
  workflow_dispatch:

jobs:
  release:
    name: ⚡ Release Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 📤 Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}