name: Publish Release ✨

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build-deb
    steps:
      - name: Checkout repo 📥
        uses: actions/checkout@v3

      - name: Download .deb artifact 📦
        uses: actions/download-artifact@v4
        with:
          name: nginx-party-deb
          path: ./release

      - name: Create GitHub Release 🎉
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb to Release 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-build notes 📝
        run: |
          echo "🎉 NGINX-PARTY Release published!"
          echo "- .deb artifact attached 📦"
          echo "- Docker images pushed to Docker Hub 🐳 & GHCR 🌟"
          echo "- Contributors: update secrets if you fork 🔑"
          echo "- Pull Docker images:"
          echo "  Docker Hub: docker pull \$DOCKER_USERNAME/nginx-party:latest"
          echo "  GHCR: docker pull ghcr.io/\$GITHUB_REPOSITORY_OWNER/nginx-party:latest"
          echo "🐛 If something broke, check CI logs carefully!"
