name: 🐼 Release Build & Upload 📦

on:
  push:
    tags:
      - "v*.*.*"

env:
  NGINX_VERSION: 1.29.1
  OPENSSL_VERSION: 3.3.1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🐼 Checkout code
        uses: actions/checkout@v4

      - name: 🗄️ Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: release-${{ env.NGINX_VERSION }}-${{ github.ref_name }}

      - name: 🔧 Build Release Binary
        run: |
          export CC="ccache gcc"
          export CXX="ccache g++"
          export PATH="/usr/lib/ccache:$PATH"
          echo "Building release version..."
          # (Insert same configure/make steps from ci.yml here)

      - name: 📦 Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-release
          path: /usr/local/nginx/sbin/nginx