name: 📝 NGINX-PARTY Release Notes & Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐧 Get Current Version
        run: |
          echo "Current version: $GITHUB_REF"
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 📝 Generate Release Notes
        run: |
          gh release create $VERSION --title "NGINX-PARTY $VERSION" --notes "Automated build with stable + QUIC + AVIF/WEBP + Mods + ModSecurity"

      - name: 📦 Attach DEB & Docker Info
        run: |
          echo "Attach DEB packages and Docker info manually or via artifacts"