name: 🛰️ Release NGINX-PARTY

on:
  workflow_dispatch:

jobs:
  release:
    name: 📤 Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 📤 Upload DEB
        uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-party:stable