name-template: "NGINX-PARTY v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - feature
      - enhancement
  - title: "🐛 Fixes"
    labels:
      - bug
      - fix
  - title: "🛠 Maintenance"
    labels:
      - chore
      - build
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## 🚀 What's New
  $CHANGES

  ## 🔧 Install
  Download `.deb` from Assets below and install:

  ```bash
  sudo dpkg -i nginx-party_*.deb
  sudo apt-get -f install
