name: 🐼 NGINX-PARTY Release 🎁

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 📦 Download CI artifacts
        uses: actions/download-artifact@v4
        with:
          name: nginx-artifacts
          path: ./artifacts

      - name: 📝 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: nginx-party-artifacts-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: 🎉 Release complete
        run: echo "🐼 NGINX-PARTY release created with artifacts!"
