name: 🎉 Release NGINX-PARTY

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 📦 Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
          docker tag nginx-party:latest ${{ secrets.DOCKERHUB_USER }}/nginx-party:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USER }}/nginx-party:${{ github.ref_name }}