name: NGINX-PARTY Release Automation 🐼🚀⚡

on:
  workflow_dispatch:
  push:
    tags:
      - "nginx-party-stable-v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 📦 Create release notes
        run: |
          echo "Release: $GITHUB_REF_NAME" > release_notes.txt
          echo "NGINX-PARTY stable build with QUIC + Mods" >> release_notes.txt

      - name: 🔐 Login Docker & GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 🐳 Build & push Docker images
        run: |
          docker build -t nginx-party:$GITHUB_REF_NAME .
          docker tag nginx-party:$GITHUB_REF_NAME docker.io/${{ secrets.DOCKER_HUB_USER }}/nginx-party:$GITHUB_REF_NAME
          docker push docker.io/${{ secrets.DOCKER_HUB_USER }}/nginx-party:$GITHUB_REF_NAME
          docker tag nginx-party:$GITHUB_REF_NAME ghcr.io/${{ github.repository_owner }}/nginx-party:$GITHUB_REF_NAME
          docker push ghcr.io/${{ github.repository_owner }}/nginx-party:$GITHUB_REF_NAME

      - name: 📝 Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "NGINX-PARTY ${{ github.ref_name }}"
          body_path: release_notes.txt
