name: 🎉 PANDUH-PARTY Release ⚡🌐🕶️

on:
  push:
    tags:
      - 'nginx-party-stable-v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🐼 Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 💾 Restore NGINX build cache
        uses: actions/cache@v4
        with:
          path: /usr/local/nginx
          key: nginx-build-${{ env.NGINX_VERSION }}

      - name: 📦 Package NGINX as DEB
        run: |
          cd packaging
          ./build-deb.sh
          cd ..

      - name: 🐳 Build Docker image
        run: |
          docker build \
            --build-arg NGINX_PATH=/usr/local/nginx \
            -t ${{ secrets.DOCKER_HUB_USER }}/nginx-party:${GITHUB_REF_NAME} \
            -t ghcr.io/${{ github.repository }}/nginx-party:${GITHUB_REF_NAME} \
            .

      - name: 🚀 Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/nginx-party:${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository }}/nginx-party:${GITHUB_REF_NAME}
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: 📝 Create Release Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: NGINX-PARTY Release ${{ github.ref_name }}
          body: |
            Stable NGINX-PARTY build with:
            - NGINX 1.29.1
            - QUIC + HTTP/3
            - ModSecurity
            - Brotli, Cache Purge, FancyIndex
            - AVIF/WEBP, WebSockets, Rust support
            - Optimized build flags & security
