name: 🛰️ Release NGINX-PARTY

on:
  workflow_run:
    workflows: ["⚡ CI - Build & Test NGINX-PARTY"]
    types:
      - completed

jobs:
  release:
    name: 🛰️ Publish Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 📤 Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}