name: PANDUH-PARTY Release 🎁🛠️🚀

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-panduh-party
          path: ./nginx-panduh-party_${{ env.NGINX_VERSION }}-1_amd64.deb

      - name: 🏷️ Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "PANDUH-PARTY ${{ github.ref_name }}"
          artifacts: nginx-panduh-party_${{ env.NGINX_VERSION }}-1_amd64.deb
