name: 🐼 NGINX-PARTY Release Automation

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Checkout repo
        uses: actions/checkout@v4

      - name: 🎁 Download CI artifacts
        uses: actions/download-artifact@v4
        with:
          name: nginx-artifacts
          path: release/

      - name: 🐼 Prepare release package
        run: |
          echo "Preparing NGINX-PARTY release tarball..."
          tar -czf nginx-party-release.tar.gz -C release .

      - name: 📦 Upload release to GitHub
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: nginx-party-release.tar.gz
          asset_name: nginx-party-release.tar.gz
          asset_content_type: application/gzip
