name: 🎉 PANDUH-PARTY Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 📝 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "nginx-party-stable-${{ github.ref_name }} 🚀"
          body: |
            Release ${{ github.ref_name }} ready.
            Includes NGINX 1.29.1 + QUIC + ModSecurity + Brotli + Cache modules.

      - name: 📦 Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-party-deb
          path: nginx-*.deb

      - name: 🐳 Push Docker Images
        uses: ./.github/workflows/docker.yml