name: 🚀 Release NGINX-PARTY Stable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: ✨ Build & Release Deb + Docker
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: 🛠️ Run CI Build
        uses: ./.github/workflows/ci.yml

      - name: 📦 Package Deb
        run: |
          mkdir -p dist
          # Simple deb build placeholder; expand for proper packaging
          echo "NGINX-PARTY v${GITHUB_REF_NAME}" > dist/nginx-party.txt

      - name: 🐳 Build & Push Docker
        uses: ./.github/workflows/docker.yml