name: 🏷️ NGINX-PARTY Release 🚀

on:
  push:
    tags:
      - 'nginx-party-stable-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🛠️ Build release notes
        run: |
          echo "Generating release notes..."
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD > release_notes.md
          echo "✅ Release notes generated"

      - name: 🐳 Build Docker release
        run: docker build -t nginx-party-stable:${GITHUB_REF##*/} .

      - name: 🚀 Push Docker & GHCR release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag nginx-party-stable:${GITHUB_REF##*/} $DOCKER_USERNAME/nginx-party-stable:${GITHUB_REF##*/}
          docker push $DOCKER_USERNAME/nginx-party-stable:${GITHUB_REF##*/}
          echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag nginx-party-stable:${GITHUB_REF##*/} ghcr.io/${GITHUB_REPOSITORY}:nginx-party-stable-${GITHUB_REF##*/}
          docker push ghcr.io/${GITHUB_REPOSITORY}:nginx-party-stable-${GITHUB_REF##*/}
